# azure-pipelines.yml

trigger:
  branches:
    exclude:
      - '*'

pr: none

jobs:
- job: BuildAndPushDockerImage
  displayName: 'Build and Push Docker Image'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self

  - script: docker build -t hw:$(Build.BuildId) .
    displayName: 'Build Docker Image'
    # workingDirectory: .

  - script: docker login -u $(username) -p $(password)
    displayName: 'Docker Login'
    
  - script: docker tag hw:$(Build.BuildId) $(username)/hw:$(Build.BuildId)
    displayName: 'Tag Docker Image'
  
  - script: docker push $(username)/hw:$(Build.BuildId)
    displayName: 'Push Docker Image to Docker Hub'
