# azure-pipelines.yml

trigger:
  branches:
    exclude:
      - '*'

pr: none

jobs:
- job: BuildAndPushDockerImage
  displayName: 'Build and Push Docker Image'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self

  - script: docker build -t hw:v1 .
    displayName: 'Build Docker Image'
    workingDirectory: .

  - script: docker login -u $(username) -p $(password) <your_docker_registry>
    displayName: 'Docker Login'
  
#   - script: docker push <your_docker_image_name>:<your_tag>
#     displayName: 'Docker Push'
